[package]
name = "xtxc-basket-vault"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "=2.3.0"

[workspace]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
overflow-checks = true

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(target_os, values("solana"))'] }
